language: objective-c
xcode_workspace: Tesseract-OCR-iOS.xcworkspace
xcode_sdk:
    - iphonesimulator7.1
    - iphonesimulator8.1 
xcode_scheme: 
    - Template Framework Project
    - TestsProject
before_install:
    sudo pip install PyYAML; sudo pip install cpp-coveralls
after_success:
    ./scripts/coveralls.rb --extension m --extension mm --exclude-folder include --exclude-folder TestsProject

